package com.neo.v1.model.catalogue;

import lombok.AllArgsConstructor;
import lombok.Builder;

import java.util.List;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class CategoryListData {

	private List<CategoryDetail> merchantCategories;


  public CategoryListData() {
    super();
  }

  /* Getters */

	public List<CategoryDetail> getMerchantCategories() { return this.merchantCategories; }


  /* Setters */

	public void setMerchantCategories(List<CategoryDetail> merchantCategories) { this.merchantCategories = merchantCategories; };


  public static class Builder {

    private CategoryListData item = new CategoryListData();

		public Builder withMerchantCategories(List<CategoryDetail> merchantCategories) { item.setMerchantCategories(merchantCategories); return this; };


    public CategoryListData build() {
      return item;
    }

  }


}
