package com.neo.v1.model.catalogue;

import com.neo.v1.transactions.enrichment.model.Meta;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class CategoryListResponse {

	private Meta meta;

	private CategoryListData data;


  public CategoryListResponse() {
    super();
  }

  /* Getters */

	public Meta getMeta() { return this.meta; }

	public CategoryListData getData() { return this.data; }


  /* Setters */

	public void setMeta(Meta meta) { this.meta = meta; };

	public void setData(CategoryListData data) { this.data = data; };


  public static class Builder {

    private CategoryListResponse item = new CategoryListResponse();

		public Builder withMeta(Meta meta) { item.setMeta(meta); return this; };

		public Builder withData(CategoryListData data) { item.setData(data); return this; };


    public CategoryListResponse build() {
      return item;
    }

  }


}
