package com.neo.v1.model.catalogue;

import lombok.AllArgsConstructor;
import lombok.Builder;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class CategoryDetail {

	private Long id;

	private String name;

	private String iconLabelUrl;

	private String icon;

	private String color;

	private Long displayOrder;


  public CategoryDetail() {
    super();
  }

  /* Getters */

	public Long getId() { return this.id; }

	public String getName() { return this.name; }

	public String getIconLabelUrl() { return this.iconLabelUrl; }

	public String getIcon() { return this.icon; }

	public String getColor() { return this.color; }

	public Long getDisplayOrder() { return this.displayOrder; }


  /* Setters */

	public void setId(Long id) { this.id = id; };

	public void setName(String name) { this.name = name; };

	public void setIconLabelUrl(String iconLabelUrl) { this.iconLabelUrl = iconLabelUrl; };

	public void setIcon(String icon) { this.icon = icon; };

	public void setColor(String color) { this.color = color; };

	public void setDisplayOrder(Long displayOrder) { this.displayOrder = displayOrder; };


  public static class Builder {

    private CategoryDetail item = new CategoryDetail();

		public Builder withId(Long id) { item.setId(id); return this; };

		public Builder withName(String name) { item.setName(name); return this; };

		public Builder withIconLabelUrl(String iconLabelUrl) { item.setIconLabelUrl(iconLabelUrl); return this; };

		public Builder withIcon(String icon) { item.setIcon(icon); return this; };

		public Builder withColor(String color) { item.setColor(color); return this; };

		public Builder withDisplayOrder(Long displayOrder) { item.setDisplayOrder(displayOrder); return this; };


    public CategoryDetail build() {
      return item;
    }

  }


}
