package com.neo.v1.model.catalogue;

import com.neo.v1.transactions.enrichment.model.Meta;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class MerchantListResponse {

	private Meta meta;

	private MerchantListData data;


  public MerchantListResponse() {
    super();
  }

  /* Getters */

	public Meta getMeta() { return this.meta; }

	public MerchantListData getData() { return this.data; }


  /* Setters */

	public void setMeta(Meta meta) { this.meta = meta; };

	public void setData(MerchantListData data) { this.data = data; };


  public static class Builder {

    private MerchantListResponse item = new MerchantListResponse();

		public Builder withMeta(Meta meta) { item.setMeta(meta); return this; };

		public Builder withData(MerchantListData data) { item.setData(data); return this; };


    public MerchantListResponse build() {
      return item;
    }

  }


}
