package com.neo.v1.model.catalogue;

import com.neo.v1.transactions.enrichment.model.Meta;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class MerchantCodeListResponse {

	private Meta meta;

	private MerchantCodeListData data;


  public MerchantCodeListResponse() {
    super();
  }

  /* Getters */

	public Meta getMeta() { return this.meta; }

	public MerchantCodeListData getData() { return this.data; }


  /* Setters */

	public void setMeta(Meta meta) { this.meta = meta; };

	public void setData(MerchantCodeListData data) { this.data = data; };


  public static class Builder {

    private MerchantCodeListResponse item = new MerchantCodeListResponse();

		public Builder withMeta(Meta meta) { item.setMeta(meta); return this; };

		public Builder withData(MerchantCodeListData data) { item.setData(data); return this; };


    public MerchantCodeListResponse build() {
      return item;
    }

  }


}
