package com.neo.v1.model.catalogue;

import lombok.AllArgsConstructor;
import lombok.Builder;

import java.util.List;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class MerchantCodeListData {

	private List<MerchantCodeDetail> merchantCodes;


  public MerchantCodeListData() {
    super();
  }

  /* Getters */

	public List<MerchantCodeDetail> getMerchantCodes() { return this.merchantCodes; }


  /* Setters */

	public void setMerchantCodes(List<MerchantCodeDetail> merchantCodes) { this.merchantCodes = merchantCodes; };


  public static class Builder {

    private MerchantCodeListData item = new MerchantCodeListData();

		public Builder withMerchantCodes(List<MerchantCodeDetail> merchantCodes) { item.setMerchantCodes(merchantCodes); return this; };


    public MerchantCodeListData build() {
      return item;
    }

  }


}
