package com.neo.v1.model.catalogue;

import lombok.AllArgsConstructor;
import lombok.Builder;

import java.util.List;

/**
* Auto generated by ila/neo 1.2.0
*/
@Builder
@AllArgsConstructor
public class MerchantListData {

	private List<MerchantDetail> merchants;


  public MerchantListData() {
    super();
  }

  /* Getters */

	public List<MerchantDetail> getMerchants() { return this.merchants; }


  /* Setters */

	public void setMerchants(List<MerchantDetail> merchants) { this.merchants = merchants; };


  public static class Builder {

    private MerchantListData item = new MerchantListData();

		public Builder withMerchants(List<MerchantDetail> merchants) { item.setMerchants(merchants); return this; };


    public MerchantListData build() {
      return item;
    }

  }


}
