package com.neo.v1.enums;

public enum GlobalConfig {
    URBIS_NARRATIVE_CODE,
    CREATE_HOLD_EXPIRY_DATE_DAYS_ADD_COUNT,

    SOURCE_SYSTEM,
    HOLD_VALUE_INDICATOR,
    TMSX_ACCOUNT_TRANSACTION_LOCAL_STATUS,
    TMSX_ACCOUNT_TRANSACTION_STATUS,
    TMSX_ACCOUNT_TRANSACTION_STATUS_PENDING,
    TMSX_ACCOUNT_TRANSACTION_STATUS_FAILED,
    TMSX_ACCOUNT_TRANSACTION_RECONCILIATION_STATUS,
    TMSX_ACCOUNT_TRANSACTION_DIRECTION,
    TMSX_ACCOUNT_TRANSACTION_DIRECTION_INCOMING,
    TMSX_ACCOUNT_TRANSACTION_DIRECTION_OUTGOING,
    TMSX_BANK_OPERATION_CODE,
    TMSX_FROM_DATE_INTERVAL,
    TMSX_TO_DATE_INTERVAL,
    TMSX_HOLD_TYPE,
    ENABLE_THROTTLING

}
