replicaCount: 1

image:
  repository: 096987977627.dkr.ecr.eu-west-1.amazonaws.com/api/transactions-enrichment-service
  tag: latest
  pullPolicy: Always

nameOverride: "transactions-enrichment-service"
fullnameOverride: "transactions-enrichment-service"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  paths:
    - /api/v1/transaction-enrichment
    - /transaction-enrichment

aws:
  role: service-default-role

appdynamics:
  appdynamics_controller_host_name: null
  appdynamics_agent_account_name: null
  appdynamics_agent_account_access_key: null
  appdynamics_agent_application_name: api-dev
  appdynamics_java_agent_reuse_node_name: True
  appdynamics_controller_port: 443
  appdynamics_controller_ssl_enabled: True

env:
  pg_write_db_host: null
  pg_read_db_host: null
  pg_db_name: neo_service_transactions_enrichment
  pg_db_password: null
  pg_db_username: null

  te:
    account:
      service:
        base:
          url: http://accounts-service.accounts-service.svc:8080/api/v1/accounts
    charity:
      service:
        base:
          url: http://charity-service.charity-service.svc:8080/api/v1/charity
    transaction:
      service:
        base:
          url: http://transactions-service.transactions-service.svc:8080/api/v1/transactions
    product:
      service:
        base:
          url: http://product-catalogue-service.product-catalogue-service.svc:8080/api/v1/product-catalogue


  spring:
    profiles:
      active: dev

